# test_a1.tavern.yaml

test_name: test healthcheck

stages:
  - name: test the a1 healthcheck
    request:
      url: http://localhost:10000/a1-p/healthcheck
      method: GET
    response:
      status_code: 200

---

test_name: test admission control

stages:
  - name: test the admission control policy get not there yet
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy
      method: GET
    response:
      status_code: 404

  - name: test the admission control policy status get not there yet
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy/status
      method: GET
    response:
      status_code: 404

  - name: test the admission control policy
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy
      method: PUT
      json:
        enforce: true
        window_length: 10
        blocking_rate: 20
        trigger_threshold: 10
      headers:
        content-type: application/json
    response:
      status_code: 201

  - name: test the admission control policy get
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy
      method: GET
    response:
      status_code: 200
      body:
        enforce: true
        window_length: 10
        blocking_rate: 20
        trigger_threshold: 10

  - name: test the admission control policy status get
    delay_before: 3 # give it a few seconds for rmr
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy/status
      method: GET
    response:
      status_code: 200
      body:
        - handler_id: test_receiver
          status: OK

---

test_name: test the delay receiver

stages:
  - name: test the delay policy get not there yet
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/delaytest
      method: GET
    response:
      status_code: 404

  - name: test the delay policy status get not there yet
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/delaytest/status
      method: GET
    response:
      status_code: 404

  - name: test the delay policy
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/delaytest
      method: PUT
      json: {}
      headers:
        content-type: application/json
    response:
      status_code: 201

  - name: test the delay policy get
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/delaytest
      method: GET
    response:
      status_code: 200
      body: {}

  - name: test the admission control policy status get
    delay_before: 8  # give it a few seconds for rmr ; delay reciever sleeps for 5 seconds by default
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/delaytest/status
      method: GET
    response:
      status_code: 200
      body:
        - handler_id: delay_receiver
          status: OK




---

test_name: bad_requests

stages:

  - name: bad body for admission control policy
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy
      method: PUT
      json:
        not: "expected"
      headers:
        content-type: application/json
    response:
      status_code: 400

  - name: not a json
    request:
      url: http://localhost:10000/a1-p/policytypes/20000/policies/admission_control_policy
      method: PUT
      data: "asdf"
    response:
      status_code: 415

  - name: bad body for test policy
    request:
      url: http://localhost:10000/a1-p/policytypes/20001/policies/test_policy
      method: PUT
      json:
        not: "welcome"
    response:
      status_code: 400
